### ISSUE TITLE
Minor improvements to static analysis

### ISSUE THREAD

**Issue by IanMayo** [debrief/limpet#233]
@pecko - I _think_ that our step to combine the different static reports only happens in the Travis build (in deploy_ghpages.sh).  

But, it would be useful to have the separate project reports combined into one folder for local builds aswell.

So, could you change the maven build so that the outputs get combined into one folder locally?

I guess this is just moving some steps from .sh to the maven build.

**Comment by pecko** [comment]
The PR: https://github.com/debrief/limpet/pull/243

You can run

```
mvn clean verify site
```

After that reports will be in YOUR_LIMPET_REPO_HOME/reports/static/index.html

I have to add a new module (pure maven without Java code): info.limpet.report, because reports have to be created after building other maven modules (plugins).

I will merge the PR in order to test travis.

**Comment by pecko** [comment]
Travis is fine. Reports on github are in old place: http://debrief.github.io/limpet-update/static/report/

@IanMayo 

Please review and if it's OK, close issue.

**Comment by IanMayo** [comment]
Hmm, **mvn clean verify site** is failing for me:

[INFO] Scanning for projects...
[ERROR] Internal error: java.lang.RuntimeException: Could not resolve target platform specification artifact info.limpet:eclipse38:target:1.0.6-SNAPSHOT -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: Could not resolve target platform specification artifact info.limpet:eclipse38:target:1.0.6-SNAPSHOT
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.RuntimeException: Could not resolve target platform specification artifact info.limpet:eclipse38:target:1.0.6-SNAPSHOT
    at org.eclipse.tycho.core.resolver.DefaultTargetPlatformConfigurationReader.addTargetArtifact(DefaultTargetPlatformConfigurationReader.java:389)
    at org.eclipse.tycho.core.resolver.DefaultTargetPlatformConfigurationReader.setTarget(DefaultTargetPlatformConfigurationReader.java:342)
    at org.eclipse.tycho.core.resolver.DefaultTargetPlatformConfigurationReader.getTargetPlatformConfiguration(DefaultTargetPlatformConfigurationReader.java:75)
    at org.eclipse.tycho.core.resolver.DefaultTychoResolver.setupProject(DefaultTychoResolver.java:86)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:90)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:266)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    ... 11 more
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException

**Comment by pecko** [comment]
Sorry, I have forgot. After the commit related to qualifier you have to install target platform once:

```
cd info.limpet.targetplatforms
mvn clean install
cd ..
mvn clean verify site
```

**Comment by IanMayo** [comment]
ok, that makes it run.

I now get the **reports/static/report\*  folder, with **index.html** inside it.  This opens the list of  sets of reports (starting with code coverage).  But, only the code coverage link works. The others are "this web page has not been found" - so I guess the separate blocks of reports havne't been copied into this new structure.

**Comment by pecko** [comment]
I thought I check it... Will look at that later

**Comment by pecko** [comment]
It works for me (mvn clean verify site on master).
My local limpet repository is **/home/snpe/projects/limpet** and I use 

file:///home/snpe/projects/limpet/reports/static/report/index.html

Remote URL:  http://debrief.github.io/limpet-update/static/report/ uses the same structure.

Could you please check again?

**Comment by IanMayo** [comment]
OK, will check again.

**Comment by pecko** [comment]
@IanMayo 
I think that this issue can be closed.
