### ISSUE TITLE
StackedCharts crash when try to move around (zoom in/out) 

### ISSUE THREAD

**Issue by theanuradha** [debrief/limpet#406]
java.lang.NumberFormatException: empty String
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1011)
	at java.lang.Double.parseDouble(Double.java:540)
	at info.limpet.stackedcharts.ui.view.ChartBuilder$RedGreenAngularUnitAxis.getTickLabelPaintFor(ChartBuilder.java:1262)
	at info.limpet.stackedcharts.ui.view.ChartBuilder$RedGreenAngularUnitAxis.drawTickMarksAndLabels(ChartBuilder.java:1147)
	at org.jfree.chart.axis.NumberAxis.draw(NumberAxis.java:666)
	at org.jfree.chart.plot.XYPlot.drawAxes(XYPlot.java:3656)
	at org.jfree.chart.plot.XYPlot.draw(XYPlot.java:3147)
	at org.jfree.chart.plot.CombinedDomainXYPlot.draw(CombinedDomainXYPlot.java:511)
	at info.limpet.stackedcharts.ui.view.TimeBarPlot.draw(TimeBarPlot.java:446)
	at org.jfree.chart.JFreeChart.draw(JFreeChart.java:1229)
	at org.jfree.experimental.chart.swt.ChartComposite.paintControl(ChartComposite.java:1844)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:230)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4136)

**Comment by IanMayo** [comment]
I've been using StackedCharts quite regularly.  I suspect there's something specific about the chart you've created. 

Could you tell me how you created it?

**Comment by theanuradha** [comment]
@IanMayo I it from a Track not sure I remember . will try to reproduce and give detail steps

**Comment by theanuradha** [comment]
Steps:
Open **sample_data/shapes.dpf**
Switch to **Track Tote**
select **Show tactical overview** 
Click/Point right  on top of the **Orange Maker** and **Drag to Zoom** 

then **boom**

**Comment by IanMayo** [comment]
Ok, thanks. If you need test date, sample.dpf will work.
